security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
            
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: true
                default_target_path: /admin
            logout:       true
            anonymous:    true

    access_control:
        # Specific urls with/without trailing slash
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password-reset$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # Whole directories
        - { path: ^/admin, role: ROLE_ADMIN }
