schema_author_index:
    path:     /admin/schema-author/{page}
    controller: App\Controller\SchemaAuthorController::indexAction
    methods:  GET
    requirements:
        page: '\d+'
    defaults:
        page: 1
        
schema_author_edit:
    path:     /admin/schema-author/{id}/edit
    controller: App\Controller\SchemaAuthorController::editAction
    methods:  [GET, POST]