<?php

namespace App\Repository;

/**
 * PluginVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JVZooProductRepository extends \Doctrine\ORM\EntityRepository {

    use BaseRepository;

    public $entity = 'JVZooProduct';

 
}
