<?php

namespace App\Repository;

/**
 * PluginVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PluginVersionRepository extends \Doctrine\ORM\EntityRepository {

    use BaseRepository;

    public $entity = 'PluginVersion';

    public function checkForHigherReleaseUpdateVersion($version, $entity) {
        $this->getQb();

        $this->qb->where("obj.version >= :version")->setParameter('version', $version);

        if ($entity && $entity->getId()) {
            $this->qb->andWhere("obj.id != :id")->setParameter('id', $entity);
        }

        return $this->getSingleResult();
    }

    public function getLatestVersion() {
        $this->getQb();

        $this->qb->orderBy('obj.version', 'DESC');
        return $this->getSingleResult();
    }

}
